// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhSz_f7yPEz5S-qw_D2EvoQvLPt1DPD8',
    appId: '1:182986357178:web:458452f54fc2af7b3bc583',
    messagingSenderId: '182986357178',
    projectId: 'estella-flutterapp',
    authDomain: 'estella-flutterapp.firebaseapp.com',
    storageBucket: 'estella-flutterapp.firebasestorage.app',
    measurementId: 'G-6LSCYF5E1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGC5r7-3Ik4caTHU4KJCKVENmbAUPP44A',
    appId: '1:182986357178:android:da60485eff5effce3bc583',
    messagingSenderId: '182986357178',
    projectId: 'estella-flutterapp',
    storageBucket: 'estella-flutterapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDChOA2UpB5qT_FvBwQq1sCR-hB0lYNvw',
    appId: '1:182986357178:ios:cccdee24e56aa10f3bc583',
    messagingSenderId: '182986357178',
    projectId: 'estella-flutterapp',
    storageBucket: 'estella-flutterapp.firebasestorage.app',
    iosBundleId: 'com.example.estella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDChOA2UpB5qT_FvBwQq1sCR-hB0lYNvw',
    appId: '1:182986357178:ios:cccdee24e56aa10f3bc583',
    messagingSenderId: '182986357178',
    projectId: 'estella-flutterapp',
    storageBucket: 'estella-flutterapp.firebasestorage.app',
    iosBundleId: 'com.example.estella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArhSz_f7yPEz5S-qw_D2EvoQvLPt1DPD8',
    appId: '1:182986357178:web:06ab3e35ff827a103bc583',
    messagingSenderId: '182986357178',
    projectId: 'estella-flutterapp',
    authDomain: 'estella-flutterapp.firebaseapp.com',
    storageBucket: 'estella-flutterapp.firebasestorage.app',
    measurementId: 'G-EM7BMC6K31',
  );
}
